# Generated by Django 3.1.4 on 2021-05-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_moviedata_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='typ',
            field=models.CharField(default='actions', max_length=100),
        ),
    ]
